apiVersion: v1
kind: Service
metadata:
  name: snap-socket-server
  labels:
    app: snap-socket-server
spec:
  selector:
    app: snap-socket-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
